name: ci

on:
  pull_request:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
      - run: echo "VERSION_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: echo $VERSION_TAG
      - run: echo ${{ env.VERSION_TAG }}
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18.x"
      - run: go install github.com/laher/goxc@latest golang.org/x/lint/golint@latest
      - run: ghr -u Arthur1 -r tag-action-test $VERSION_TAG dist/
